import formsPlugin from '@tailwindcss/forms';
import containerQueriesPlugin from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './menu.html',
    './privacy.html',
    './terms.html',
    './src/**/*.{js,ts,jsx,tsx,css}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#38393c',
        'on-secondary-fixed': '#281900',
        'primary-fixed-dim': '#ffb4a1',
        'surface-container-highest': '#343538',
        'outline': '#a88a83',
        'tertiary-fixed-dim': '#b9cbb9',
        'on-tertiary-fixed-variant': '#3b4b3d',
        'primary-fixed': '#ffdbd1',
        'on-tertiary-fixed': '#101f13',
        'surface-variant': '#343538',
        'on-surface-variant': '#e1bfb7',
        'on-secondary-container': '#3a2600',
        'inverse-surface': '#e3e2e6',
        'primary-container': '#f1643e',
        'surface-dim': '#121316',
        'on-secondary-fixed-variant': '#604100',
        'on-surface': '#e3e2e6',
        'error-container': '#93000a',
        'inverse-primary': '#ac3311',
        'tertiary-container': '#849585',
        'error': '#ffb4ab',
        'on-secondary': '#432c00',
        'on-background': '#e3e2e6',
        'surface-container-lowest': '#0d0e11',
        'surface-container-high': '#292a2d',
        'on-error': '#690005',
        'on-tertiary': '#253427',
        'secondary-container': '#bd8718',
        'on-primary-container': '#550f00',
        'tertiary-fixed': '#d5e7d4',
        'on-tertiary-container': '#1e2d21',
        'on-primary': '#611300',
        'outline-variant': '#59413b',
        'tertiary': '#b9cbb9',
        'on-primary-fixed-variant': '#881f00',
        'on-primary-fixed': '#3c0800',
        'surface-tint': '#ffb4a1',
        'secondary-fixed-dim': '#fabc4d',
        'secondary-fixed': '#ffdead',
        'surface-container': '#1f1f23',
        'surface': '#121316',
        'on-error-container': '#ffdad6',
        'primary': '#ffb4a1',
        'inverse-on-surface': '#2f3034',
        'surface-container-low': '#1b1b1f',
        'secondary': '#fabc4d',
        'background': '#121316',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        margin: '3rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        'space-2xl': '4rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'display-hero': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'headline-sm': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        'label-caps': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        'body-sm': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'display-hero-mobile': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        'headline-lg': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'headline-md': ['Playfair Display', 'Georgia', 'Cambria', 'Times New Roman', 'serif'],
      },
    },
  },
  plugins: [formsPlugin, containerQueriesPlugin],
};
